name = "news-api"
main = "index.js"
compatibility_date = "2025-06-05"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
ENVIRONMENT = "development"

[env.development]
[[env.development.d1_databases]]
binding = "NEWS_DB"
database_name = "news-db"
database_id = "5e914ae6-5b03-469d-8a34-63643280ef36"

[env.development.vars]
JWT_SECRET = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
ENVIRONMENT = "development"

[env.production]
[[env.production.d1_databases]]
binding = "NEWS_DB"
database_name = "news-db"
database_id = "5e914ae6-5b03-469d-8a34-63643280ef36"

[env.production.vars]
JWT_SECRET = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
ENVIRONMENT = "production"